package com.ada.dynamo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;

public interface DynamoDBEntity {
    void setId(String id);
}
